---
version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex:${PLEX_TAG:-1.27.2}
    environment:
      DOCKER_MODS: ${DOCKER_MODS:-linuxserver/mods:plex-absolute-hama}
      PGID: ${PGID:-1000}
      PLEX_CLAIM:
      PUID: ${PUID:-1000}
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${CONFIG_VOLUME:-config}:/config
      - ${MEDIA_VOLUME:-media}:/media
volumes:
  config:
  media:
